### ISSUE TITLE
gemfile requires ruby 2.1.0

### ISSUE THREAD

**Issue by teslaji** [starterkits/rails4-starterkit#8]
Since I am using windows 8 platform, there is no rubyinstaller support for ruby 2.1.0. Similarly no rvm for windows. I don't know other options to upgrade to 2.1. Please show me the workaround. currently I have ruby 2.0.0 installed.

**Comment by hilfans** [comment]
@kbhatt2006 

please try tu run: gem install pg -v '0.17.1' -- --with-pg-config=/usr/pgsql-9.3/bin/pg_config

and than you can run again: bundle install

I have the same problem with you, and that command it's works for me
